


import streamlit as st
import pandas as pd
import joblib

st.set_page_config(
    page_title="Bike Rental Demand Prediction",
    page_icon="🚲",
    layout="centered"
)

@st.cache_resource
def load_artifacts():
    model = joblib.load("bike_demand_xgb_model.pkl")
    encoders = joblib.load("bike_demand_label_encoders.pkl")
    features = joblib.load("bike_demand_features.pkl")
    return model, encoders, features

try:
    model, encoders, features = load_artifacts()
except FileNotFoundError:
    st.error(
        "Model files are missing. Run the final Deployment Preparation cells "
        "in the notebook first to create the .pkl files."
    )
    st.stop()

st.title("🚲 Bike Rental Demand Prediction")
st.write(
    "Predict the expected number of bike rentals using time, weather, "
    "season and working-day information."
)

st.header("Prediction Inputs")

col1, col2 = st.columns(2)

with col1:
    year_label = st.selectbox("Year", ["2011", "2012"])
    yr = 0 if year_label == "2011" else 1

    mnth = st.slider("Month", 1, 12, 6)
    hr = st.slider("Hour", 0, 23, 8)
    weekday = st.slider("Weekday (0=Sunday, 6=Saturday)", 0, 6, 1)

    season_value = st.selectbox(
        "Season",
        list(encoders["season"].classes_)
    )

    holiday_value = st.selectbox(
        "Holiday",
        list(encoders["holiday"].classes_)
    )

with col2:
    workingday_value = st.selectbox(
        "Working Day",
        list(encoders["workingday"].classes_)
    )

    weather_value = st.selectbox(
        "Weather Situation",
        list(encoders["weathersit"].classes_)
    )

    temp = st.number_input(
        "Temperature (normalized)",
        min_value=0.0,
        max_value=1.0,
        value=0.5,
        step=0.01
    )

    atemp = st.number_input(
        "Feeling Temperature (normalized)",
        min_value=0.0,
        max_value=1.0,
        value=0.5,
        step=0.01
    )

    hum = st.number_input(
        "Humidity (normalized)",
        min_value=0.0,
        max_value=1.0,
        value=0.5,
        step=0.01
    )

    windspeed = st.number_input(
        "Wind Speed (normalized)",
        min_value=0.0,
        max_value=1.0,
        value=0.2,
        step=0.01
    )

st.subheader("Engineered Features")
day_of_month = st.slider("Day of Month", 1, 31, 15)
is_weekend = int(weekday in [0, 6])
is_rush_hour = int(hr in [7, 8, 9, 17, 18, 19])
is_night = int(hr >= 22 or hr <= 5)

st.write(
    f"Weekend: **{is_weekend}** | "
    f"Rush hour: **{is_rush_hour}** | "
    f"Night: **{is_night}**"
)

if st.button("Predict Bike Demand", type="primary"):
    try:
        input_data = pd.DataFrame({
            "season": [season_value],
            "yr": [yr],
            "mnth": [mnth],
            "hr": [hr],
            "holiday": [holiday_value],
            "weekday": [weekday],
            "workingday": [workingday_value],
            "weathersit": [weather_value],
            "temp": [temp],
            "atemp": [atemp],
            "hum": [hum],
            "windspeed": [windspeed],
            "day_of_month": [day_of_month],
            "is_weekend": [is_weekend],
            "is_rush_hour": [is_rush_hour],
            "is_night": [is_night]
        })

        for col in ["season", "holiday", "workingday", "weathersit"]:
            input_data[col] = encoders[col].transform(
                input_data[col].astype(str)
            )

        input_data = input_data[features]
        prediction = float(model.predict(input_data)[0])
        prediction = max(0, round(prediction))

        st.success(f"🚲 Predicted Bike Demand: **{prediction} bikes**")

        st.info(
            "This prediction is generated by the tuned XGBoost regression "
            "model trained in the project notebook."
        )

    except Exception as e:
        st.error(f"Prediction failed: {e}")
